spring:
  application:
    name: User-Microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/Fitness
    username: postgres
    password: Anvi@1503

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

