server:
  port: 8083

spring:
  application:
    name: AI-Microservice

#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: ${AI_DB_URI}

  jpa:
    hibernate:
      ddl-auto: update

  Kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.model.Activity
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      default: http://localhost:/8761/eureka/

Kafka:
  topic:
    name: activity-events

gemini_url: ${GEMINI_URL}
gemini_key: ${GEMINI_KEY}
